// Code generated by `generate`. DO NOT EDIT.

package kittycad

import "net/http"

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.kittycad.io for example.
	server string

	// Client is the *http.Client for performing requests.
	client *http.Client

	// token is the API token used for authentication.
	token string
	// File: CAD file operations.
	File *FileService
	// Meta: Meta information about servers, instances, and sessions.
	Meta *MetaService
	// Internal: Internal API endpoints.
	Internal *InternalService
}

// FileService: CAD file operations.
type FileService service

// MetaService: Meta information about servers, instances, and sessions.
type MetaService service

// InternalService: Internal API endpoints.
type InternalService service
