// Code generated by `generate`. DO NOT EDIT.

package kittycad_test

import (
	"fmt"

	"github.com/kittycad/kittycad.go"
)

// Create a client with your token.
func ExampleNewClient() {
	client, err := kittycad.NewClient("$TOKEN", "your apps user agent")
	if err != nil {
		panic(err)
	}

	// Call the client's methods.
	resp, err := client.Meta.Ping()
	if err != nil {
		panic(err)
	}

	fmt.Println(resp)
}

// - OR -

// Create a new client with your token parsed from the environment
// variable: `KITTYCAD_API_TOKEN`.
func ExampleNewClientFromEnv() {
	client, err := kittycad.NewClientFromEnv("your apps user agent")
	if err != nil {
		panic(err)
	}

	// Call the client's methods.
	resp, err := client.Meta.Ping()
	if err != nil {
		panic(err)
	}

	fmt.Println(resp)
}
